# Generated by Django 5.0.7 on 2024-07-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
